# Generated by Django 6.0.6 on 2026-06-19 13:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperchatSyncRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('discover', 'Discover updates'), ('extract', 'Extract approved'), ('full', 'Full sync')], default='discover', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('discovering', 'Discovering'), ('waiting_approval', 'Waiting approval'), ('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], default='pending', max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('total_checked', models.IntegerField(default=0)),
                ('candidates_found', models.IntegerField(default=0)),
                ('total_to_extract', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('current_conversation_id', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Superchat Sync Run',
                'verbose_name_plural': 'Superchat Sync Runs',
                'db_table': 'superchat_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SuperchatSyncCandidate',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(max_length=120)),
                ('superchat_status', models.CharField(blank=True, max_length=80, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=120, null=True)),
                ('channel_type', models.CharField(blank=True, max_length=80, null=True)),
                ('inbox_id', models.CharField(blank=True, max_length=120, null=True)),
                ('inbox_name', models.CharField(blank=True, max_length=255, null=True)),
                ('superchat_url', models.TextField(blank=True, null=True)),
                ('local_exists', models.BooleanField(default=False)),
                ('local_last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('superchat_open_until', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('extract_status', models.CharField(choices=[('pending', 'Pending'), ('exporting', 'Exporting'), ('export_pending', 'Export pending'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('parsed', 'Parsed'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('export_id', models.CharField(blank=True, max_length=120, null=True)),
                ('export_status', models.CharField(blank=True, max_length=80, null=True)),
                ('export_link', models.TextField(blank=True, null=True)),
                ('export_link_valid_until', models.DateTimeField(blank=True, null=True)),
                ('zip_path', models.TextField(blank=True, null=True)),
                ('pdf_path', models.TextField(blank=True, null=True)),
                ('messages_found', models.IntegerField(default=0)),
                ('attachments_found', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='superchatsync.superchatsyncrun')),
            ],
            options={
                'verbose_name': 'Superchat Sync Candidate',
                'verbose_name_plural': 'Superchat Sync Candidates',
                'db_table': 'superchat_sync_candidates',
                'ordering': ['created_at'],
                'unique_together': {('run', 'conversation_id')},
            },
        ),
    ]
