# Generated manually for Peeko/business-client knowledge workspace.

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superchatsync", "0007_order_eur_estimates"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessClient",
            fields=[
                ("business_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.TextField()),
                ("domain", models.TextField(blank=True, null=True)),
                ("default_language", models.CharField(default="en", max_length=12)),
                ("default_currency", models.CharField(blank=True, max_length=10, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("paused", "Paused"), ("archived", "Archived")], default="draft", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Client",
                "verbose_name_plural": "Business Clients",
                "db_table": "business_clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessKnowledgeImportRun",
            fields=[
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_url", models.TextField()),
                ("source_type", models.CharField(default="website_crawl", max_length=40)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="draft", max_length=30)),
                ("pages_found", models.IntegerField(default=0)),
                ("pages_crawled", models.IntegerField(default=0)),
                ("products_found", models.IntegerField(default=0)),
                ("products_imported", models.IntegerField(default=0)),
                ("knowledge_items_created", models.IntegerField(default=0)),
                ("media_assets_created", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_import_runs", to="superchatsync.businessclient")),
            ],
            options={
                "verbose_name": "Business Knowledge Import Run",
                "verbose_name_plural": "Business Knowledge Import Runs",
                "db_table": "business_knowledge_import_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessProduct",
            fields=[
                ("product_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=220)),
                ("name", models.TextField()),
                ("url", models.TextField(blank=True, null=True)),
                ("vendor", models.TextField(blank=True, null=True)),
                ("product_type", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("options", models.JSONField(blank=True, default=list)),
                ("variants", models.JSONField(blank=True, default=list)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("min_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("max_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")], default="draft", max_length=30)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="superchatsync.businessclient")),
            ],
            options={
                "verbose_name": "Business Product",
                "verbose_name_plural": "Business Products",
                "db_table": "business_products",
                "ordering": ["business", "name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessCrawlPage",
            fields=[
                ("page_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("url", models.TextField()),
                ("url_hash", models.CharField(max_length=64)),
                ("canonical_url", models.TextField(blank=True, null=True)),
                ("page_type", models.CharField(default="page", max_length=40)),
                ("title", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=12)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("extracted_char_count", models.IntegerField(default=0)),
                ("text_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("crawled", "Crawled"), ("error", "Error"), ("skipped", "Skipped")], default="draft", max_length=30)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("crawled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crawl_pages", to="superchatsync.businessclient")),
                ("import_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="crawl_pages", to="superchatsync.businessknowledgeimportrun")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="crawl_pages", to="superchatsync.businessproduct")),
            ],
            options={
                "verbose_name": "Business Crawl Page",
                "verbose_name_plural": "Business Crawl Pages",
                "db_table": "business_crawl_pages",
                "ordering": ["business", "page_type", "url"],
            },
        ),
        migrations.CreateModel(
            name="BusinessKnowledgeItem",
            fields=[
                ("item_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope", models.CharField(choices=[("general", "General"), ("category", "Category"), ("product", "Product")], default="general", max_length=30)),
                ("item_type", models.CharField(choices=[("general_policy", "General policy"), ("brand_voice", "Brand voice"), ("product_fact", "Product fact"), ("product_benefit", "Product benefit"), ("product_usage", "Product usage"), ("product_specs", "Product specs"), ("product_faq", "Product FAQ"), ("pricing_offer", "Pricing / offer"), ("objection_answer", "Objection answer"), ("raw_section", "Raw section")], max_length=40)),
                ("title", models.TextField(blank=True, null=True)),
                ("question", models.TextField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, null=True)),
                ("body", models.TextField()),
                ("evidence", models.TextField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                ("source_url_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("source_section", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=12)),
                ("confidence_score", models.IntegerField(default=75)),
                ("priority", models.IntegerField(default=50)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("rejected", "Rejected"), ("archived", "Archived")], default="draft", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reviewed_by", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_items", to="superchatsync.businessclient")),
                ("import_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_items", to="superchatsync.businessknowledgeimportrun")),
                ("page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_items", to="superchatsync.businesscrawlpage")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_items", to="superchatsync.businessproduct")),
            ],
            options={
                "verbose_name": "Business Knowledge Item",
                "verbose_name_plural": "Business Knowledge Items",
                "db_table": "business_knowledge_items",
                "ordering": ["business", "scope", "item_type", "-confidence_score", "title"],
            },
        ),
        migrations.CreateModel(
            name="BusinessMediaAsset",
            fields=[
                ("asset_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("asset_type", models.CharField(default="image", max_length=30)),
                ("image_role", models.CharField(default="unknown", max_length=40)),
                ("title", models.TextField(blank=True, null=True)),
                ("alt_text", models.TextField(blank=True, null=True)),
                ("source_url", models.TextField()),
                ("source_url_hash", models.CharField(max_length=64)),
                ("local_path", models.TextField(blank=True, null=True)),
                ("mime_type", models.TextField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("source_page_url", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=12)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("rejected", "Rejected"), ("archived", "Archived")], default="draft", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_assets", to="superchatsync.businessclient")),
                ("import_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_assets", to="superchatsync.businessknowledgeimportrun")),
                ("page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_assets", to="superchatsync.businesscrawlpage")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_assets", to="superchatsync.businessproduct")),
            ],
            options={
                "verbose_name": "Business Media Asset",
                "verbose_name_plural": "Business Media Assets",
                "db_table": "business_media_assets",
                "ordering": ["business", "product", "image_role", "title"],
            },
        ),
        migrations.AddIndex(model_name="businessclient", index=models.Index(fields=["slug"], name="business_cl_slug_7be9b3_idx")),
        migrations.AddIndex(model_name="businessclient", index=models.Index(fields=["status"], name="business_cl_status_50bb7c_idx")),
        migrations.AddIndex(model_name="businessknowledgeimportrun", index=models.Index(fields=["business", "status"], name="business_kn_busines_8189de_idx")),
        migrations.AddIndex(model_name="businessknowledgeimportrun", index=models.Index(fields=["source_type"], name="business_kn_source__a54a6b_idx")),
        migrations.AddIndex(model_name="businessproduct", index=models.Index(fields=["business", "status"], name="business_pr_busines_a57bb2_idx")),
        migrations.AddIndex(model_name="businessproduct", index=models.Index(fields=["business", "name"], name="business_pr_busines_b2fcc7_idx")),
        migrations.AddConstraint(model_name="businessproduct", constraint=models.UniqueConstraint(fields=("business", "slug"), name="uniq_business_product_slug")),
        migrations.AddConstraint(model_name="businessproduct", constraint=models.UniqueConstraint(condition=models.Q(("external_id__isnull", False)), fields=("business", "external_id"), name="uniq_business_product_external_id")),
        migrations.AddIndex(model_name="businesscrawlpage", index=models.Index(fields=["business", "page_type"], name="business_cr_busines_e9f47e_idx")),
        migrations.AddIndex(model_name="businesscrawlpage", index=models.Index(fields=["business", "status"], name="business_cr_busines_13a749_idx")),
        migrations.AddIndex(model_name="businesscrawlpage", index=models.Index(fields=["text_hash"], name="business_cr_text_ha_204602_idx")),
        migrations.AddConstraint(model_name="businesscrawlpage", constraint=models.UniqueConstraint(fields=("business", "url_hash"), name="uniq_business_crawl_page_url_hash")),
        migrations.AddIndex(model_name="businessknowledgeitem", index=models.Index(fields=["business", "status"], name="business_kn_busines_13701a_idx")),
        migrations.AddIndex(model_name="businessknowledgeitem", index=models.Index(fields=["business", "scope", "item_type"], name="business_kn_busines_837162_idx")),
        migrations.AddIndex(model_name="businessknowledgeitem", index=models.Index(fields=["product", "item_type"], name="business_kn_product_d84760_idx")),
        migrations.AddConstraint(model_name="businessknowledgeitem", constraint=models.UniqueConstraint(fields=("business", "source_url_hash", "item_type", "content_hash"), name="uniq_business_knowledge_source_hash")),
        migrations.AddIndex(model_name="businessmediaasset", index=models.Index(fields=["business", "status"], name="business_me_busines_8cd44f_idx")),
        migrations.AddIndex(model_name="businessmediaasset", index=models.Index(fields=["product", "image_role"], name="business_me_product_9d4a86_idx")),
        migrations.AddIndex(model_name="businessmediaasset", index=models.Index(fields=["asset_type"], name="business_me_asset_t_29e41e_idx")),
        migrations.AddConstraint(model_name="businessmediaasset", constraint=models.UniqueConstraint(fields=("business", "source_url_hash"), name="uniq_business_media_source_hash")),
    ]
