FITEXPRESS_COUNTRIES = [
    {"country_id": 1001, "country_name": "Romania", "iso2": "RO", "phone_prefixes": ["+40"], "default_language": "ro"},
    {"country_id": 1044, "country_name": "Moldova", "iso2": "MD", "phone_prefixes": ["+373"], "default_language": "ro"},
    {"country_id": 1081, "country_name": "Bulgaria", "iso2": "BG", "phone_prefixes": ["+359"], "default_language": "bg"},
    {"country_id": 1109, "country_name": "Czech", "iso2": "CZ", "phone_prefixes": ["+420"], "default_language": "cs"},
    {"country_id": 1186, "country_name": "Poland", "iso2": "PL", "phone_prefixes": ["+48"], "default_language": "pl"},
    {"country_id": 1300, "country_name": "Slovakia", "iso2": "SK", "phone_prefixes": ["+421"], "default_language": "sk"},
    {"country_id": 1400, "country_name": "Ukraine", "iso2": "UA", "phone_prefixes": ["+380"], "default_language": "uk"},
    {"country_id": 1500, "country_name": "Hungary", "iso2": "HU", "phone_prefixes": ["+36"], "default_language": "hu"},
    {"country_id": 1600, "country_name": "United Kingdom", "iso2": "GB", "phone_prefixes": ["+44"], "default_language": "en"},
    {"country_id": 1700, "country_name": "Germany", "iso2": "DE", "phone_prefixes": ["+49"], "default_language": "de"},
    {"country_id": 1800, "country_name": "Turkey", "iso2": "TR", "phone_prefixes": ["+90"], "default_language": "tr"},
    {"country_id": 1801, "country_name": "Italy", "iso2": "IT", "phone_prefixes": ["+39"], "default_language": "it"},
    {"country_id": 1802, "country_name": "Spain", "iso2": "ES", "phone_prefixes": ["+34"], "default_language": "es"},
    {"country_id": 1803, "country_name": "Serbia", "iso2": "RS", "phone_prefixes": ["+381"], "default_language": "sr"},
    {"country_id": 1804, "country_name": "Vietnam", "iso2": "VN", "phone_prefixes": ["+84"], "default_language": "vi"},
    {"country_id": 1805, "country_name": "Singapore", "iso2": "SG", "phone_prefixes": ["+65"], "default_language": "en"},
    {"country_id": 1806, "country_name": "Mexico", "iso2": "MX", "phone_prefixes": ["+52"], "default_language": "es"},
    {"country_id": 1807, "country_name": "Indonesia", "iso2": "ID", "phone_prefixes": ["+62"], "default_language": "id"},
    {"country_id": 1808, "country_name": "Greece", "iso2": "GR", "phone_prefixes": ["+30"], "default_language": "el"},
    {
        "country_id": 1809,
        "country_name": "Vietnam adult",
        "iso2": "VN",
        "phone_prefixes": [],
        "default_language": "vi",
        "metadata": {"note": "Special Fitexpress region; select by campaign/account context, not phone prefix alone."},
    },
    {"country_id": 1810, "country_name": "Undefined", "iso2": None, "phone_prefixes": [], "default_language": None},
    {"country_id": 1811, "country_name": "France", "iso2": "FR", "phone_prefixes": ["+33"], "default_language": "fr"},
    {"country_id": 1812, "country_name": "Portugal", "iso2": "PT", "phone_prefixes": ["+351"], "default_language": "pt"},
    {"country_id": 1813, "country_name": "Austria", "iso2": "AT", "phone_prefixes": ["+43"], "default_language": "de"},
    {"country_id": 1814, "country_name": "Croatia", "iso2": "HR", "phone_prefixes": ["+385"], "default_language": "hr"},
    {"country_id": 1815, "country_name": "Slovenia", "iso2": "SI", "phone_prefixes": ["+386"], "default_language": "sl"},
    {"country_id": 1816, "country_name": "Egypt", "iso2": "EG", "phone_prefixes": ["+20"], "default_language": "ar"},
    {"country_id": 1817, "country_name": "Nigeria", "iso2": "NG", "phone_prefixes": ["+234"], "default_language": "en"},
    {"country_id": 1818, "country_name": "Kenya", "iso2": "KE", "phone_prefixes": ["+254"], "default_language": "en"},
    {"country_id": 1819, "country_name": "Saudi Arabia", "iso2": "SA", "phone_prefixes": ["+966"], "default_language": "ar"},
    {"country_id": 1820, "country_name": "USA", "iso2": "US", "phone_prefixes": ["+1"], "default_language": "en"},
    {"country_id": 1821, "country_name": "Belgium", "iso2": "BE", "phone_prefixes": ["+32"], "default_language": "fr"},
    {"country_id": 1822, "country_name": "Netherlands", "iso2": "NL", "phone_prefixes": ["+31"], "default_language": "nl"},
    {"country_id": 1823, "country_name": "Ireland", "iso2": "IE", "phone_prefixes": ["+353"], "default_language": "en"},
    {"country_id": 1824, "country_name": "Switzerland", "iso2": "CH", "phone_prefixes": ["+41"], "default_language": "de"},
    {"country_id": 1825, "country_name": "Colombia", "iso2": "CO", "phone_prefixes": ["+57"], "default_language": "es"},
]


FITEXPRESS_PRODUCT_MAPPINGS = [
    {
        "product_id": "2054",
        "product_name": "Epilage",
        "fitexpress_product_id": "2054",
        "aliases": ["Epilage"],
        "landing_url": "https://beautyshopfan.com/epilage/ro2/v3/",
    },
    {
        "product_id": "2151",
        "product_name": "Foam Cleaner",
        "fitexpress_product_id": "2151",
        "aliases": ["FoamCleaner"],
        "landing_url": "https://wyzexpress.com/foamcleaner/ro2/",
        "metadata": {
            "alternative_ids": [
                {"fitexpress_product_id": "2214", "name": "Foam Cleaner Liquid"},
                {"fitexpress_product_id": "2399", "name": "Foam Cleaner LP"},
            ],
            "note": "Use 2151 unless campaign explicitly points to Liquid or LP.",
        },
    },
    {
        "product_id": "2424",
        "product_name": "Venzen cushion",
        "fitexpress_product_id": "2424",
        "aliases": ["Cushion"],
        "landing_url": "https://venzencushion.com/ro2/v4/",
        "metadata": {
            "alternative_ids": [{"fitexpress_product_id": "2434", "name": "Venzen cushion LP"}],
            "note": "Use 2424 unless campaign explicitly points to LP.",
        },
    },
    {
        "product_id": "2463",
        "product_name": "Magnetic Eyelashes",
        "fitexpress_product_id": "2463",
        "aliases": ["Magnetic Eyelashes"],
        "landing_url": "https://wyzshops.com/magnetieyelashes/christmas/ro/",
    },
    {
        "product_id": "2490",
        "product_name": "Gramophone",
        "fitexpress_product_id": "2490",
        "aliases": ["FERON"],
        "landing_url": "https://wyzshops.com/feron/ro/v3/",
    },
    {
        "product_id": "2561",
        "product_name": "Japanese knife",
        "fitexpress_product_id": "2561",
        "aliases": ["Tazaki"],
        "landing_url": "https://tazaki.co/bg/laser2/v3/",
        "metadata": {"localization_warning": "Live landing scanned from BG URL; check language before import."},
    },
    {
        "product_id": "2565",
        "product_name": "ScratchSprayRemover",
        "fitexpress_product_id": "2565",
        "aliases": ["Spray de vopsea auto"],
        "landing_url": "https://scratchspray.com/ro/survey/simple/",
    },
    {
        "product_id": "2584",
        "product_name": "Gold Collagen Capsules",
        "fitexpress_product_id": "2584",
        "aliases": ["CSK"],
        "landing_url": "https://beautyshopfan.com/goldcollagencapsules/ro2/v4/",
    },
    {
        "product_id": "2652",
        "product_name": "Beef Knife",
        "fitexpress_product_id": "2652",
        "aliases": ["Toji", "Toji - Cutit din otel japonez calit"],
        "landing_url": "https://beefknife.com/ro/v7/",
    },
    {
        "product_id": "2658",
        "product_name": "Windshield Wiper",
        "fitexpress_product_id": "2658",
        "aliases": ["Rainaway"],
        "landing_url": "https://rainawaywipers.com/ro/",
    },
    {
        "product_id": "2687",
        "product_name": "Cut Knife",
        "fitexpress_product_id": "2687",
        "aliases": ["PrimeCut", "PrimeCut - Cutit Profesional de Taiere"],
        "landing_url": "https://primecutknife.shop/ro/",
    },
    {
        "product_id": "2691",
        "product_name": "Tanto Double Knife",
        "fitexpress_product_id": "2691",
        "aliases": ["Tanto Knifes", "Tanto Knife"],
        "landing_url": "https://tanto-knife.com/ro/v2/",
    },
    {
        "product_id": "2716",
        "product_name": "Axium",
        "fitexpress_product_id": "2716",
        "aliases": ["AXIUM"],
        "landing_url": "https://wyzshops.com/axium/ro/v5/full/",
    },
    {
        "product_id": "2720",
        "product_name": "Crafix",
        "fitexpress_product_id": "2720",
        "aliases": ["CRAFIX"],
        "landing_url": "https://wyzexpress.com/crafix/ro/v5/",
    },
    {
        "product_id": "2722",
        "product_name": "Kirami Japan Knife",
        "fitexpress_product_id": "2722",
        "aliases": ["Kirami", "Kirami - Cutit japonez"],
        "landing_url": "https://wyzshops.com/kirami/ro/",
    },
    {
        "product_id": "2735",
        "product_name": "GritMaster",
        "fitexpress_product_id": "2735",
        "aliases": ["GritMaster"],
        "landing_url": "https://wyzshops.com/gritmaster/ro/v5/",
    },
    {
        "product_id": "2737",
        "product_name": "Torasei",
        "fitexpress_product_id": "2737",
        "aliases": ["TORASEI"],
        "landing_url": "https://wyzshops.com/torasei/ro/v6/",
    },
    {
        "product_id": "2757",
        "product_name": "ButchAxe",
        "fitexpress_product_id": "2757",
        "aliases": ["BUTCHAXE"],
        "landing_url": "https://wyzshops.com/butchaxe/ro/",
        "metadata": {
            "source_of_truth": "landing",
            "source_of_truth_url": "https://wyzshops.com/butchaxe/ro/",
            "correct_material": "7CR17MOV-X",
            "knowledge_guardrail": "For ButchAxe, landing content is correct. Do not reintroduce the old 154-CM material claim from older docs.",
        },
    },
    {
        "product_id": "2779",
        "product_name": "Marmora",
        "fitexpress_product_id": "2779",
        "aliases": ["MARMORA", "MARMORA - Acoperire epoxidica"],
        "landing_url": "https://wyzshops.com/marmora/ro/v5/",
    },
    {
        "product_id": "2888",
        "product_name": "Nuvia Trimmer",
        "fitexpress_product_id": "2888",
        "aliases": ["NUVIA 2 in 1", "Trimmer electric pentru femei"],
        "landing_url": "https://wyzshops.com/nuvia/ro2/",
        "options": {"Color": ["pink", "khaki"]},
    },
    {
        "product_id": "2921",
        "product_name": "Set M20 M25 M32",
        "fitexpress_product_id": "2921",
        "aliases": ["Set pentru filetarea tevilor PPR 20/25/32 mm"],
        "landing_url": "https://wyzshops.com/pipeset/ro/",
    },
]
